import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import "../styles/globals.css";
import { Sidebar } from "../components/layout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable} font-sans`}>
        <Sidebar />
        <main id="main" className="pl-[80px] lg:pl-[240px] transition-all">
          {children}
        </main>
      </body>
    </html>
  );
}
